import { chromium } from 'playwright-core'
const S = process.argv[2]
const b = await chromium.launch({ channel: 'chrome', headless: true })
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 } })
const p = await ctx.newPage()
const errs = []
p.on('pageerror', e => errs.push('pageerror: ' + e.message)); p.on('console', m => { if (['error','warning'].includes(m.type())) errs.push(m.type() + ': ' + m.text()) })
// work filter FLIP
await p.goto('http://localhost:3210/work', { waitUntil: 'networkidle' })
await p.getByRole('button', { name: 'Weddings & portraits' }).click(); await p.waitForTimeout(150)
await p.screenshot({ path: `${S}/shots3/flip-mid.png`, clip: { x: 0, y: 300, width: 1440, height: 700 } })
await p.waitForTimeout(500); console.log('filtered count', await p.locator('.workgrid .work').count(), 'url', p.url())
await p.getByRole('button', { name: 'All work' }).click(); await p.waitForTimeout(600); console.log('all count', await p.locator('.workgrid .work').count())
// case navigation with view transition
console.log('VT supported', await p.evaluate(() => 'startViewTransition' in document))
await p.locator('.work').first().click(); await p.waitForTimeout(200)
await p.screenshot({ path: `${S}/shots3/vt-mid.png` })
await p.waitForTimeout(800); console.log('case url', p.url(), 'vt name on hero', await p.locator('.plate.ar-21-9').evaluate(e => getComputedStyle(e).viewTransitionName))
await p.goBack(); await p.waitForTimeout(900); console.log('back url', p.url())
// wizard: forward/back, odometer, count-up, calendar paging
await p.goto('http://localhost:3210/booking', { waitUntil: 'networkidle' })
await p.getByLabel('Photoshoot Sessions', { exact: false }).first().check({ force: true })
await p.getByRole('button', { name: 'Choose a date' }).click(); await p.waitForTimeout(400)
await p.getByRole('button', { name: 'Next month' }).click(); await p.waitForTimeout(120)
await p.screenshot({ path: `${S}/shots3/cal-mid.png`, clip: { x: 0, y: 200, width: 900, height: 700 } })
await p.waitForTimeout(400); console.log('month', await p.locator('.calmonth').textContent())
await p.locator('button.calday:not([disabled])').first().click()
await p.getByLabel('09:00').check({ force: true })
await p.getByRole('button', { name: 'Add-ons' }).click(); await p.waitForTimeout(500)
for (let i = 0; i < 5; i++) await p.getByRole('button', { name: 'More Additional photo' }).click()
await p.waitForTimeout(80); await p.screenshot({ path: `${S}/shots3/odo-mid.png`, clip: { x: 0, y: 400, width: 1440, height: 500 } })
await p.waitForTimeout(400); console.log('total', await p.locator('.sumtotal__b').textContent(), 'deposit', await p.locator('.deposit b').textContent(), 'qty', await p.locator('.stepval').first().textContent())
await p.getByRole('button', { name: 'Fewer Additional photo' }).click(); await p.waitForTimeout(400); console.log('after fewer', await p.locator('.sumtotal__b').textContent())
await p.getByRole('button', { name: 'Your details' }).click(); await p.waitForTimeout(150)
await p.screenshot({ path: `${S}/shots3/step-fwd-mid.png`, clip: { x: 0, y: 150, width: 1440, height: 700 } })
await p.waitForTimeout(400); await p.getByRole('button', { name: '← Back' }).click(); await p.waitForTimeout(120)
await p.screenshot({ path: `${S}/shots3/step-back-mid.png`, clip: { x: 0, y: 150, width: 1440, height: 700 } })
await p.waitForTimeout(500); console.log('step heading', await p.locator('.bstep h2').first().textContent(), 'qty kept', await p.locator('.stepval').first().textContent())
// full submit still works after v-if change
await p.getByRole('button', { name: 'Your details' }).click(); await p.waitForTimeout(500)
await p.fill('#k-name', 'Mutale Banda'); await p.fill('#k-email', 'm@example.com'); await p.fill('#k-phone', '+260 96 000 0000'); await p.check('#k-terms')
await p.getByRole('button', { name: 'Review request' }).click(); await p.waitForTimeout(500)
await p.getByRole('button', { name: 'Send booking request' }).click(); await p.waitForTimeout(1600)
console.log('ref', await p.locator('.refno').textContent(), 'delivery line', (await p.locator('pre.request').textContent()).match(/Delivery.*/)[0])
// TOC scroll-spy
await p.goto('http://localhost:3210/terms', { waitUntil: 'networkidle' })
await p.locator('#t-11').scrollIntoViewIfNeeded(); await p.waitForTimeout(400)
console.log('active toc', await p.locator('.toc a.is-active').textContent())
await p.screenshot({ path: `${S}/shots3/toc.png` })
// drawer
await p.setViewportSize({ width: 390, height: 800 }); await p.goto('http://localhost:3210/', { waitUntil: 'networkidle' })
await p.getByRole('button', { name: 'Menu' }).click(); await p.waitForTimeout(100); await p.screenshot({ path: `${S}/shots3/drawer-mid.png` })
console.log('errors:', errs.length ? errs : 'none')
await b.close()
